### PR TITLE
Backport support for async backtraces

### PR DESCRIPTION
**Pull request by kpamnany**
## PR Description

Backport https://github.com/JuliaLang/julia/pull/51430.

## Checklist

Requirements for merging:
- [X] I have opened an issue or PR upstream on JuliaLang/julia: https://github.com/JuliaLang/julia/pull/51430
- [X] I have removed the `port-to-*` labels that don't apply.

### CODE REVIEW

**Comment by nickrobinson251** [comment]
I don't know how to review this 😛 

How have you tested that this works? given it is merged upstream, I'd be happy to approve so long as you've tested it works

**Comment by kpamnany** [comment]
Yeah, glad you asked. It does work fine on upstream `master`. But on our branch, it does not. I'm trying to fix it.

**Comment by kpamnany** [comment]
Fixed the build issue, but then found that this actually crashes if you run with multiple threads. Upstream fix is https://github.com/JuliaLang/julia/pull/51471.

**Comment by kpamnany** [comment]
Fixed and checked that it seems to work, even with multiple threads.

**Review by Drvi — APPROVED** [review]
Since Kiran said it works:)

**Pull request merged**
