### PR TITLE
Bring a few upstream GC patches into our fork

### PR DESCRIPTION
**Pull request by d-netto**
## PR Description

Should be NFCs or code simplifications.

https://github.com/JuliaLang/julia/pull/54936 is the only one which does more significant changes, but we already assessed its performance in the open-source benchmarks and internally as well.

## Checklist

Requirements for merging:
- [x] I have opened an issue or PR upstream on JuliaLang/julia: N/A (multiple PRs)
- [x] I have removed the `port-to-*` labels that don't apply.
- [x] I have opened a PR on raicode to test these changes: https://github.com/RelationalAI/raicode/pull/20439

### CODE REVIEW

**Comment by kpamnany** [comment]
Let's run benchmarks on this full commit set?

**Comment by d-netto** [comment]
> Let's run benchmarks on this full commit set?

Yes.

**Comment by d-netto** [comment]
Ran the benchmarks in https://github.com/RelationalAI/raicode/pull/20439.

**Review by kpamnany — APPROVED** [review]
❤️

**Pull request merged**
